INSERT INTO bands (bandName, bandPhotoURL, bandHometown, bandGenre, bandBio) 
VALUES ("The Internet", "https://static01.nyt.com/images/2018/07/19/arts/19album-internet1/merlin_141177372_a142a45e-bfc2-451c-a19d-456191f86f81-articleLarge.jpg?quality=75&auto=webp&disable=upscale", "Los Angeles, California", "Hip-hop/R&B", "The Internet is an American band from Los Angeles, California. It currently consists of vocalist Syd, keyboardist Matt Martians, bassist Patrick Paige II, drummer Christopher Smith, and guitarist Steve Lacy.  Their music is a blend of R&B, hip hop, jazz, funk, and electronic dance music. They have released four studio albums and three extended plays since their formation in late 2011. The band's 2015 album Ego Death was nominated for the Grammy Award for Best Urban Contemporary Album."),
("Tyler, The Creator", "https://images.genius.com/dd193e747f6dbb149087c3e2543d0b93.1000x1000x1.jpg", "Ladera Heights, California", "Hip-hop/R&B", "Tyler Gregory Okonma (born March 6, 1991), known professionally as Tyler, the Creator, is an American rapper, singer, songwriter, record producer, music video director, fashion designer, graphic designer, actor and comedian.[2][3][4][5] He rose to prominence in the early 2010s as the co-founder and de facto leader of alternative hip hop collective Odd Future, and has performed on and produced songs for nearly every Odd Future release.[6] As a solo artist, Tyler has released one mixtape and five studio albums, often handling most or all production himself."),
("Mac Miller", "https://en.wikipedia.org/wiki/Mac_Miller#/media/File:Mac_Miller_(7)_%E2%80%93_splash!_Festival_20_(2017)_(cropped).jpg", "Pittsburgh, Pennsylvania", "Hip-hop/R&B", "Malcolm James McCormick (January 19, 1992 – September 7, 2018), known professionally as Mac Miller, was an American rapper, singer, songwriter, and record producer. Born in Pittsburgh, Pennsylvania, Miller began his career in the city's hip hop scene in 2007, at the age of fifteen. In 2010, he signed a record deal with Pittsburgh-based independent label Rostrum Records, with whom he had his breakthrough with the mixtapes K.I.D.S. (2010) and Best Day Ever (2011).  Miller's debut studio album, Blue Slide Park (2011), became the first independently distributed album to top the US Billboard 200 since 1995. In 2013, he founded the record label imprint REMember Music. After his second studio album, Watching Movies with the Sound Off (2013), he left Rostrum and signed with the major label Warner Bros. Records in 2014. With them, he released four studio albums: GO:OD AM (2015), The Divine Feminine (2016), Swimming (2018), and the posthumous Circles (2020). For Swimming, he was posthumously nominated for a Grammy Award for Best Rap Album. He also served as a record producer for various artists, including himself, under the pseudonym Larry Fisherman."),
("Rich Brian", "http://www.modern-notoriety.com/wp-content/uploads/2019/08/66621935_2154476351518452_4191019052709929761_n.jpg", "Jakarta, Indonesia", "Hip-hop/R&B", "Brian Imanuel Soewarno (born 3 September 1999), known professionally as Rich Brian (formerly Rich Chigga), is an Indonesian rapper, singer, songwriter, and record producer. He is known for his viral debut single 'Dat $tick', which was first released in March 2016 on SoundCloud. The single was later certified gold by RIAA.[5] His debut studio album, Amen, was released in February 2018, and peaked at number 18 on the US Billboard 200.  Brian's second studio album, The Sailor, was released on 26 July 2019."),
("Jorja Smith", "https://i.ebayimg.com/00/s/MTAyNFg4MTk=/z/6ogAAOSwyKhbbNii/$_86.JPG", "Walsall, England", "Pop", "Jorja Alice Smith (born 11 June 1997) is an English singer and songwriter from Walsall, West Midlands. Jorja attended Aldridge Secondary School. She released her debut extended play, Project 11, in November 2016.Smith has released several singles since January 2016 and collaborated with other artists, including Drake, Kendrick Lamar, Kali Uchis, and Stormzy. She performed as the opening act on Bruno Mars' 24K Magic World Tour in October and November 2017.[2] Her debut studio album, Lost & Found, was released in 2018 to critical acclaim and peaked at number three on the UK Albums Chart. In 2018, Smith won the Brit Critics' Choice Award. In 2019, she was named Best British Female Artist at the 2019 Brit Awards and was also nominated for the Grammy Award for Best New Artist."),
("Toro Y Moi", "https://images.complex.com/complex/images/fl_lossy,q_auto/v1/zlrtt8jys73qz2n6twud/toro-y-moi-complex-news-david-cabrera5", "Columbia, South Carolina", "Pop", "Chaz Bear (born Chazwick Bradley Bundick; November 7, 1986), known professionally as Toro y Moi, is an American singer, songwriter, record producer and graphic designer. His music has taken on many forms since he began recording, but he is often identified with the rise of the chillwave movement in 2010 and 2011. His stage name is a multilingual expression consisting of the Spanish words toro and y (meaning 'bull' and 'and', respectively) and the French word moi (meaning'me').");


INSERT INTO tours (tourVenue, tourCity, tourState, tourDate, tourTime)
VALUES ("American Airlines Arena", "Miami", "Florida", "4/21", "7:00PM"),
("Madison Square Garden", "New York City", "New York", "4/11", "7:00PM"),
("TD Garden", "Boston", "Massachussetts", "4/17", "7:00PM");