INSERT INTO bands (bandName, bandPhotoURL, bandHometown, bandGenre, bandBio) 
VALUES ("The Internet", "https://static01.nyt.com/images/2018/07/19/arts/19album-internet1/merlin_141177372_a142a45e-bfc2-451c-a19d-456191f86f81-articleLarge.jpg?quality=75&auto=webp&disable=upscale", "Los Angeles, California", "Alternative R&B, Funk", "The Internet is an American band from Los Angeles, California. It currently consists of vocalist Syd, keyboardist Matt Martians, bassist Patrick Paige II, drummer Christopher Smith, and guitarist Steve Lacy.  Their music is a blend of R&B, hip hop, jazz, funk, and electronic dance music. They have released four studio albums and three extended plays since their formation in late 2011. The band's 2015 album Ego Death was nominated for the Grammy Award for Best Urban Contemporary Album."),
("Tyler, The Creator", "https://images.genius.com/dd193e747f6dbb149087c3e2543d0b93.1000x1000x1.jpg", "Ladera Heights, California", "Hip hop", "Tyler Gregory Okonma (born March 6, 1991), known professionally as Tyler, the Creator, is an American rapper, singer, songwriter, record producer, music video director, fashion designer, graphic designer, actor and comedian.[2][3][4][5] He rose to prominence in the early 2010s as the co-founder and de facto leader of alternative hip hop collective Odd Future, and has performed on and produced songs for nearly every Odd Future release.[6] As a solo artist, Tyler has released one mixtape and five studio albums, often handling most or all production himself."),
("Mac Miller", "https://en.wikipedia.org/wiki/Mac_Miller#/media/File:Mac_Miller_(7)_%E2%80%93_splash!_Festival_20_(2017)_(cropped).jpg", "Pittsburgh, Pennsylvania", "Hip hop, R&B", "Malcolm James McCormick (January 19, 1992 – September 7, 2018), known professionally as Mac Miller, was an American rapper, singer, songwriter, and record producer. Born in Pittsburgh, Pennsylvania, Miller began his career in the city's hip hop scene in 2007, at the age of fifteen. In 2010, he signed a record deal with Pittsburgh-based independent label Rostrum Records, with whom he had his breakthrough with the mixtapes K.I.D.S. (2010) and Best Day Ever (2011).  Miller's debut studio album, Blue Slide Park (2011), became the first independently distributed album to top the US Billboard 200 since 1995. In 2013, he founded the record label imprint REMember Music. After his second studio album, Watching Movies with the Sound Off (2013), he left Rostrum and signed with the major label Warner Bros. Records in 2014. With them, he released four studio albums: GO:OD AM (2015), The Divine Feminine (2016), Swimming (2018), and the posthumous Circles (2020). For Swimming, he was posthumously nominated for a Grammy Award for Best Rap Album. He also served as a record producer for various artists, including himself, under the pseudonym Larry Fisherman.");


INSERT INTO tours (tourVenue, tourCity, tourState, tourDate, tourTime)
VALUES ("American Airlines Arena", "Miami", "Florida", "4/21", "7:00PM"),
("American Airlines Arena", "Miami", "Florida", "4/11", "7:00PM"),
("American Airlines Arena", "Miami", "Florida", "4/17", "7:00PM")